<?php
	$cadenaConexionGlobal="conexion/conexion1.php";
	$plantilla="sistema";
	$nombreSistema="Sistema";
	$nombreArchivo="sistema";
	$mostrarErroresPHP="no"; 
	$mostrarConsultasSQL="no";
	$moduloDesarrollador="no"; 
	$RutaBase="Sistema_Cobranza_CorpoCapital";
?>